# makefile for Dingjiang use

all:
	mex getUnixTime.c -lm
	mex getUnixTimeBiasMs.c -lm
	#mex dMathMex.c dMath.c -lm
	#mex normRmex.c dMath.c  svd.c -lm
	#mex parseNatNetMex.c -lm
clean:
	rm -f *.o *.mexa64 *.mexglx
